# <span style='color:green'> <center>Entrega 1-Seasons, Races, Drivers, Constructors, Circuits and Qualifying.</center> </span>
### by: **Oliver Iñiguez..**

## Bibliotecas.

In [17]:
import requests
import json
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Seasons

In [18]:
seasons = {'season':[],
        'url':[]}
url = 'http://ergast.com/api/f1/seasons.json?limit=74'
response = requests.get(url)
content = json.loads(response.content)
for item in content['MRData']['SeasonTable']['Seasons']:
        seasons['season'].append(int(item['season']))
        seasons['url'].append(item['url'])
        
pd.DataFrame(seasons).to_csv('SeasonsE1.csv' , index=False)

## Races

In [19]:
races = {'season':[],
        'round':[],
        'raceid':[],
        'raceName':[],
        'circuitId':[],
        'latitud':[],
        'longitud':[],
        'country':[],
        'date':[],
        'url':[]}


for year in list(range(2010,2023)):
    url = 'http://ergast.com/api/f1/{}.json'
    response = requests.get(url.format(year))
    content = json.loads(response.content)
    for item in content['MRData']['RaceTable']['Races']:
        races['season'].append(int(item['season']))
        races['round'].append(int(item['round']))
        races['raceid'].append(item['season'] + '_' + item['round'])
        races['raceName'].append(item['raceName'])
        races['circuitId'].append(item['Circuit'].get('circuitId'))
        races['latitud'].append(float(item['Circuit'].get('Location').get('lat')))
        races['longitud'].append(float(item['Circuit'].get('Location').get('long')))
        races['country'].append(item['Circuit'].get('Location').get('country'))
        races['date'].append(pd.to_datetime(item['date']))
        races['url'].append(item['url'])

df = pd.DataFrame(races)        
pd.DataFrame(races).to_csv('RacesE1.csv' , index=False)
df

,season,round,raceid,raceName,circuitId,latitud,longitud,country,date,url
0,2010,1,2010_1,Bahrain Grand Prix,bahrain,26.03250,50.51060,Bahrain,2010-03-14,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...
1,2010,2,2010_2,Australian Grand Prix,albert_park,-37.84970,144.96800,Australia,2010-03-28,http://en.wikipedia.org/wiki/2010_Australian_G...
2,2010,3,2010_3,Malaysian Grand Prix,sepang,2.76083,101.73800,Malaysia,2010-04-04,http://en.wikipedia.org/wiki/2010_Malaysian_Gr...
3,2010,4,2010_4,Chinese Grand Prix,shanghai,31.33890,121.22000,China,2010-04-18,http://en.wikipedia.org/wiki/2010_Chinese_Gran...
4,2010,5,2010_5,Spanish Grand Prix,catalunya,41.57000,2.26111,Spain,2010-05-09,http://en.wikipedia.org/wiki/2010_Spanish_Gran...
...,...,...,...,...,...,...,...,...,...,...
254,2022,18,2022_18,Japanese Grand Prix,suzuka,34.84310,136.54100,Japan,2022-10-09,http://en.wikipedia.org/wiki/2022_Japanese_Gra...
255,2022,19,2022_19,United States Grand Prix,americas,30.13280,-97.64110,USA,2022-10-23,http://en.wikipedia.org/wiki/2022_United_State...
256,2022,20,2022_20,Mexico City Grand Prix,rodriguez,19.40420,-99.09070,Mexico,2022-10-30,http://en.wikipedia.org/wiki/2022_Mexican_Gran...
257,2022,21,2022_21,Brazilian Grand Prix,interlagos,-23.70360,-46.69970,Brazil,2022-11-13,http://en.wikipedia.org/wiki/2022_Brazilian_Gr...
258,2022,22,2022_22,Abu Dhabi Grand Prix,yas_marina,24.46720,54.60310,UAE,2022-11-20,http://en.wikipedia.org/wiki/2022_Abu_Dhabi_Gr...

## Drivers

In [21]:
drivers = {'driverId':[],
        'FirstName':[],
        'FamilyName':[],
        'DOB':[],
        'Nationality':[],
        'Biography':[]}
url = 'http://ergast.com/api/f1/drivers.json?limit=857'
response = requests.get(url)
content = json.loads(response.content)
for item in content['MRData']['DriverTable']['Drivers']:
        drivers['driverId'].append(str(item['driverId']))
        drivers['FirstName'].append(str(item['givenName']))
        drivers['FamilyName'].append(str(item['familyName']))
        drivers['DOB'].append((item['dateOfBirth']))
        drivers['Nationality'].append(str(item['nationality']))
        drivers['Biography'].append(item['url'])

df = pd.DataFrame(drivers)
pd.DataFrame(drivers).to_csv('DriversE1.csv' ,index=False)
df

,driverId,FirstName,FamilyName,DOB,Nationality,Biography
0,abate,Carlo,Abate,1932-07-10,Italian,http://en.wikipedia.org/wiki/Carlo_Mario_Abate
1,abecassis,George,Abecassis,1913-03-21,British,http://en.wikipedia.org/wiki/George_Abecassis
2,acheson,Kenny,Acheson,1957-11-27,British,http://en.wikipedia.org/wiki/Kenny_Acheson
3,adams,Philippe,Adams,1969-11-19,Belgian,http://en.wikipedia.org/wiki/Philippe_Adams
4,ader,Walt,Ader,1913-12-15,American,http://en.wikipedia.org/wiki/Walt_Ader
...,...,...,...,...,...,...
852,zapico,Emilio,Zapico,1944-05-27,Spanish,http://en.wikipedia.org/wiki/Emilio_Zapico
853,zhou,Guanyu,Zhou,1999-05-30,Chinese,http://en.wikipedia.org/wiki/Guanyu_Zhou
854,zonta,Ricardo,Zonta,1976-03-23,Brazilian,http://en.wikipedia.org/wiki/Ricardo_Zonta
855,zorzi,Renzo,Zorzi,1946-12-12,Italian,http://en.wikipedia.org/wiki/Renzo_Zorzi
856,zunino,Ricardo,Zunino,1949-04-13,Argentine,http://en.wikipedia.org/wiki/Ricardo_Zunino

## Constructors

In [23]:
constructors = {'constructorId':[],
        'Name':[],
        'Nationality':[],
        'url':[]}
url = 'http://ergast.com/api/f1/constructors.json?limit=211'
response = requests.get(url)
content = json.loads(response.content)
content
for item in content['MRData']['ConstructorTable']['Constructors']:
    constructors['constructorId'].append(str(item['constructorId']))
    constructors['Name'].append(str(item['name']))
    constructors['Nationality'].append(str(item['nationality']))
    constructors['url'].append(item['url'])
    
df = pd.DataFrame(constructors)
pd.DataFrame(constructors).to_csv('ConstructorsE1.csv', index = False)
df

,constructorId,Name,Nationality,url
0,adams,Adams,American,http://en.wikipedia.org/wiki/Adams_(constructor)
1,afm,AFM,German,http://en.wikipedia.org/wiki/Alex_von_Falkenha...
2,ags,AGS,French,http://en.wikipedia.org/wiki/Automobiles_Gonfa...
3,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...
4,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
...,...,...,...,...
206,watson,Watson,American,http://en.wikipedia.org/wiki/A.J._Watson
207,wetteroth,Wetteroth,American,http://en.wikipedia.org/wiki/Wetteroth
208,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
209,wolf,Wolf,Canadian,http://en.wikipedia.org/wiki/Walter_Wolf_Racing
210,zakspeed,Zakspeed,German,http://en.wikipedia.org/wiki/Zakspeed

## Circuits

In [25]:
circuits = {'circuitId':[],
        'CircuitName':[],
        'Locality':[],
        'Country':[],
        'Latitude':[],
        'Longitude':[],
        'url':[]}
url = 'http://ergast.com/api/f1/circuits.json?limit=77'
response = requests.get(url)
content = json.loads(response.content)
for item in content['MRData']['CircuitTable']['Circuits']:
        circuits['circuitId'].append(str(item['circuitId']))
        circuits['CircuitName'].append(str(item['circuitName']))
        circuits['Locality'].append(str(item['Location'].get('locality')))
        circuits['Country'].append(str(item['Location'].get('country')))
        circuits['Latitude'].append(float(item['Location'].get('lat')))
        circuits['Longitude'].append(float(item['Location'].get('long')))
        circuits['url'].append(item['url'])

df = pd.DataFrame(circuits)
pd.DataFrame(circuits).to_csv('CircuitsE1.csv', index = False)
df

,circuitId,CircuitName,Locality,Country,Latitude,Longitude,url
0,adelaide,Adelaide Street Circuit,Adelaide,Australia,-34.9272,138.61700,http://en.wikipedia.org/wiki/Adelaide_Street_C...
1,ain-diab,Ain Diab,Casablanca,Morocco,33.5786,-7.68750,http://en.wikipedia.org/wiki/Ain-Diab_Circuit
2,aintree,Aintree,Liverpool,UK,53.4769,-2.94056,http://en.wikipedia.org/wiki/Aintree_Motor_Rac...
3,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.96800,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
4,americas,Circuit of the Americas,Austin,USA,30.1328,-97.64110,http://en.wikipedia.org/wiki/Circuit_of_the_Am...
...,...,...,...,...,...,...,...
72,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.60310,http://en.wikipedia.org/wiki/Yas_Marina_Circuit
73,yeongam,Korean International Circuit,Yeongam County,Korea,34.7333,126.41700,http://en.wikipedia.org/wiki/Korean_Internatio...
74,zandvoort,Circuit Park Zandvoort,Zandvoort,Netherlands,52.3888,4.54092,http://en.wikipedia.org/wiki/Circuit_Zandvoort
75,zeltweg,Zeltweg,Styria,Austria,47.2039,14.74780,http://en.wikipedia.org/wiki/Zeltweg_Airfield
76,zolder,Zolder,Heusden-Zolder,Belgium,50.9894,5.25694,http://en.wikipedia.org/wiki/Zolder

## Qualifying

In [ ]:
qualifying = {'Year':[],
        'round':[],
        'raceId':[],
        'qualifyid':[],
        'RaceName':[],
        'driverId':[],     
        'Number':[],
        'Position':[],
        'constructorId':[],
        'Q1':[],
        'Q2':[],
        'Q3':[]}

urls = []

for i in list(range(2010,2023)):
    url1 = 'http://ergast.com/api/f1/'
    url2 = url1 + str(i)
    url3 = url2 + '.json'
    response = requests.get(url3)
    content = json.loads(response.content)
    for i in list(range(1,len(content['MRData']['RaceTable']['Races'])+1)):
        url4 = url2 + '/' +str(i) + '/qualifying.json' 
        urls.append(url4)
        
for j in urls:
    response = requests.get(j)
    content=json.loads(response.content)
    for m1 in content['MRData']['RaceTable']['Races']:
        for m2 in content['MRData']['RaceTable']['Races'][0]['QualifyingResults']:
            qualifying['Year'].append(int(m1['season']))
            qualifying['round'].append(int(m1['round']))
            qualifying['raceId'].append(m1['season'] + '_' + m1['round'])
            qualifying['qualifyid'].append('Qualifying' + '_'+ m1['season'] + '_' + m1['round'] )
            qualifying['RaceName'].append(str(m1['raceName']))
            qualifying['driverId'].append(str(m2['Driver'].get('driverId')))
            qualifying['Number'].append(int(m2['number']))
            qualifying['Position'].append(int(m2['position']))
            qualifying['constructorId'].append(str(m2['Constructor'].get('constructorId')))
            qualifying['Q1'].append(m2['Q1'])
            try:
                qualifying['Q2'].append(m2['Q2'])
            except:
                qualifying['Q2'].append('')
            try:
                qualifying['Q3'].append(m2['Q3'])
            except:
                qualifying['Q3'].append('')

df = pd.DataFrame(qualifying)
df.to_csv('Qualifying.csv', index =False)
df