# <span style='color:green'> <center>Entrega 3-lapTimes-driverStandings-constructorStandings constructorResults.</center> </span>
### by: **Oliver Iñiguez.**

In [1]:
import requests
import json
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## LapTimes

In [97]:
LapTimes = {'year':[],
        'round':[],
        'RaceName':[],
        'raceId':[],
        'driverId':[],  
        'lap':[],
        'position':[],
        'time':[]}

urls = []
for i in list(range(2010,2023)):
    url1 = 'http://ergast.com/api/f1/'
    url2 = url1 + str(i)
    url3 = url2 + '.json'
    response = requests.get(url3)
    content = json.loads(response.content)
    for i in list(range(1,len(content['MRData']['RaceTable']['Races'])+1)):
        url4 = url2 + '/' +str(i) + '/laps.json?limit=1000' 
        urls.append(url4)

for j in urls:
    response = requests.get(j)
    content=json.loads(response.content)
    for m1 in content['MRData']['RaceTable']['Races']:
        for m2 in content['MRData']['RaceTable']['Races'][0]['Laps']:
            for m3 in m2['Timings']:
                LapTimes['year'].append(int(m1['season']))
                LapTimes['RaceName'].append(str(m1['raceName']))
                LapTimes['round'].append(int(m1['round']))
                LapTimes['raceId'].append(m1['season'] + '_' + m1['round'])
                LapTimes['position'].append(int(m3['position']))
                LapTimes['driverId'].append(str(m3['driverId']))
                LapTimes['lap'].append(int(m2['number']))
                LapTimes['time'].append(m3['time'])

df = pd.DataFrame(LapTimes)
df.to_csv('LapTimesE3.csv', index = False)
df

,year,round,RaceName,raceId,driverId,lap,position,time
0,2010,1,Bahrain Grand Prix,2010_1,vettel,1,1,2:03.366
1,2010,1,Bahrain Grand Prix,2010_1,alonso,1,2,2:05.394
2,2010,1,Bahrain Grand Prix,2010_1,massa,1,3,2:06.758
3,2010,1,Bahrain Grand Prix,2010_1,rosberg,1,4,2:08.063
4,2010,1,Bahrain Grand Prix,2010_1,hamilton,1,5,2:08.558
...,...,...,...,...,...,...,...,...
249875,2022,22,Abu Dhabi Grand Prix,2022_22,latifi,51,19,1:32.250
249876,2022,22,Abu Dhabi Grand Prix,2022_22,max_verstappen,52,1,1:30.461
249877,2022,22,Abu Dhabi Grand Prix,2022_22,leclerc,52,2,1:29.727
249878,2022,22,Abu Dhabi Grand Prix,2022_22,perez,52,3,1:28.972
249879,2022,22,Abu Dhabi Grand Prix,2022_22,hamilton,52,4,1:30.375

## DriverStandings

In [100]:
DriverStandings = {'year':[],
        'round':[],
        'raceId':[],
        'driverStandingsId':[],
        'driverId':[],  
        'points':[],
        'position':[],
        'positionText':[],
        'wins':[]}
urls = []
for i in list(range(2010,2023)):
    url1 = 'http://ergast.com/api/f1/'
    url2 = url1 + str(i)
    url3 = url2 + '.json'
    response = requests.get(url3)
    content = json.loads(response.content)
    for i in list(range(1,len(content['MRData']['RaceTable']['Races'])+1)):
        url4 = url2 + '/' +str(i) + '/driverStandings.json?limit=1000' 
        urls.append(url4)
for j in urls:
    response = requests.get(j)
    content=json.loads(response.content)
    for m1 in content['MRData']['StandingsTable']['StandingsLists']: 
        for m2 in content['MRData']['StandingsTable']['StandingsLists'][0]['DriverStandings']:
            DriverStandings['year'].append(int(m1['season']))
            DriverStandings['round'].append(int(m1['round']))
            DriverStandings['raceId'].append(m1['season'] + '_' + m1['round'])
            DriverStandings['driverStandingsId'].append('Standings' + '_' + m1['season'] + '_' + m1['round'])
            DriverStandings['position'].append(int(m2['position']))
            DriverStandings['positionText'].append(str(m2['positionText']))
            DriverStandings['driverId'].append(str(m2['Driver']['driverId']))
            DriverStandings['points'].append(float(m2['points']))
            DriverStandings['wins'].append(int(m2['wins']))
                            
df = pd.DataFrame(DriverStandings)
df.to_csv('DriverStandingsE3.csv', index = False)
df

,year,round,raceId,driverStandingsId,driverId,points,position,positionText,wins
0,2010,1,2010_1,Standings_2010_1,alonso,25.0,1,1,1
1,2010,1,2010_1,Standings_2010_1,massa,18.0,2,2,0
2,2010,1,2010_1,Standings_2010_1,hamilton,15.0,3,3,0
3,2010,1,2010_1,Standings_2010_1,vettel,12.0,4,4,0
4,2010,1,2010_1,Standings_2010_1,rosberg,10.0,5,5,0
...,...,...,...,...,...,...,...,...,...
5762,2022,22,2022_22,Standings_2022_22,zhou,6.0,18,18,0
5763,2022,22,2022_22,Standings_2022_22,albon,4.0,19,19,0
5764,2022,22,2022_22,Standings_2022_22,latifi,2.0,20,20,0
5765,2022,22,2022_22,Standings_2022_22,de_vries,2.0,21,21,0
5766,2022,22,2022_22,Standings_2022_22,hulkenberg,0.0,22,22,0

## ConstructorStandings

In [102]:
ConstructorStandings = {'year':[],
        'round':[],
        'raceId':[],
        'constructorStandingsId':[],
        'constructorId':[],  
        'points':[],
        'position':[],
        'positionText':[],
        'wins':[]}
urls = []
for i in list(range(2010,2023)):
    url1 = 'http://ergast.com/api/f1/'
    url2 = url1 + str(i)
    url3 = url2 + '.json'
    response = requests.get(url3)
    content = json.loads(response.content)
    for i in list(range(1,len(content['MRData']['RaceTable']['Races'])+1)):
        url4 = url2 + '/' +str(i) + '/constructorstandings.json?limit=1000' 
        urls.append(url4)
for j in urls:
    response = requests.get(j)
    content=json.loads(response.content)
    for m1 in content['MRData']['StandingsTable']['StandingsLists']: 
        for m2 in content['MRData']['StandingsTable']['StandingsLists'][0]['ConstructorStandings']:
            ConstructorStandings['year'].append(int(m1['season']))
            ConstructorStandings['round'].append(int(m1['round']))
            ConstructorStandings['raceId'].append(m1['season'] + '_' + m1['round'])
            ConstructorStandings['constructorStandingsId'].append('ConstructorStanding' + '_' + 
                                        m1['season'] + '_' + m1['round'])
            ConstructorStandings['position'].append(int(m2['position']))
            ConstructorStandings['positionText'].append(str(m2['positionText']))
            ConstructorStandings['constructorId'].append(str(m2['Constructor']['constructorId']))
            ConstructorStandings['points'].append(float(m2['points']))
            ConstructorStandings['wins'].append(int(m2['wins']))
df = pd.DataFrame(ConstructorStandings)
df.to_csv('ConstructorStandingsE3.csv', index = False)
df

,year,round,raceId,constructorStandingsId,constructorId,points,position,positionText,wins
0,2010,1,2010_1,ConstructorStanding_2010_1,ferrari,43.0,1,1,1
1,2010,1,2010_1,ConstructorStanding_2010_1,mclaren,21.0,2,2,0
2,2010,1,2010_1,ConstructorStanding_2010_1,mercedes,18.0,3,3,0
3,2010,1,2010_1,ConstructorStanding_2010_1,red_bull,16.0,4,4,0
4,2010,1,2010_1,ConstructorStanding_2010_1,force_india,2.0,5,5,0
...,...,...,...,...,...,...,...,...,...
2756,2022,22,2022_22,ConstructorStanding_2022_22,alfa,55.0,6,6,0
2757,2022,22,2022_22,ConstructorStanding_2022_22,aston_martin,55.0,7,7,0
2758,2022,22,2022_22,ConstructorStanding_2022_22,haas,37.0,8,8,0
2759,2022,22,2022_22,ConstructorStanding_2022_22,alphatauri,35.0,9,9,0
2760,2022,22,2022_22,ConstructorStanding_2022_22,williams,8.0,10,10,0

## ConstructorResults

In [240]:
Data = {'position':[],
        'constructorId':[],
        'points':[],
       'year':[],
       'RaceName':[],
       'round':[],
       'raceId':[]}
DataFrame = pd.DataFrame(Data)
DataFrame = DataFrame.set_index('constructorId')
urls = []
for i in list(range(2010,2023)):
    url1 = 'http://ergast.com/api/f1/'
    url2 = url1 + str(i)
    url3 = url2 + '.json'
    response = requests.get(url3)
    content = json.loads(response.content)
    for i in list(range(1,len(content['MRData']['RaceTable']['Races'])+1)):
        url4 = url2 + '/' +str(i) + '/results.json?limit=1000' 
        urls.append(url4)
for j in urls:
    ConstructorResults = {'constructorId':[],  
                           'points':[]}
    response = requests.get(j)
    content = json.loads(response.content)
    for m1 in content['MRData']['RaceTable']['Races']:
        for m2 in content['MRData']['RaceTable']['Races'][0]['Results']:
            ConstructorResults['constructorId'].append(str(m2['Constructor']['constructorId']))
            ConstructorResults['points'].append(float(m2['points']))
        df = pd.DataFrame(ConstructorResults)
        df2 = pd.DataFrame(df.groupby('constructorId').sum().sort_values('points',ascending = False))
    RaceYear = {'RaceName':[],
                'position':[],
            'year':[],
            'round':[],
            'raceId':[]}
    for i in list(range(0,len(df2))):
        RaceYear['round'].append(m1['round'])
        RaceYear['RaceName'].append(m1['raceName'])
        RaceYear['year'].append(m1['season'])
        RaceYear['raceId'].append(m1['season'] + '_' + m1['round'])
        RaceYear['position'].append(int(i+1))

    df2['year'] = RaceYear['year']
    df2['RaceName'] = RaceYear['RaceName']
    df2['round'] = RaceYear['round']
    df2['raceId'] = RaceYear['raceId']
    df2['position'] = RaceYear['position']
    DataFrame =  pd.concat([DataFrame,df2])

DataFrame.to_csv('ConstructorResultsE3.csv', index = True)
DataFrame

               position  points  year              RaceName round   raceId
constructorId
ferrari             1.0    43.0  2010    Bahrain Grand Prix     1   2010_1
mclaren             2.0    21.0  2010    Bahrain Grand Prix     1   2010_1
mercedes            3.0    18.0  2010    Bahrain Grand Prix     1   2010_1
red_bull            4.0    16.0  2010    Bahrain Grand Prix     1   2010_1
force_india         5.0     2.0  2010    Bahrain Grand Prix     1   2010_1
...                 ...     ...   ...                   ...   ...      ...
aston_martin        6.0     5.0  2022  Abu Dhabi Grand Prix    22  2022_22
alfa                7.0     0.0  2022  Abu Dhabi Grand Prix    22  2022_22
alphatauri          8.0     0.0  2022  Abu Dhabi Grand Prix    22  2022_22
haas                9.0     0.0  2022  Abu Dhabi Grand Prix    22  2022_22
williams           10.0     0.0  2022  Abu Dhabi Grand Prix    22  2022_22

[2759 rows x 6 columns]

### Otra forma para construir esta tabla es directamente  desde la tabla results

In [3]:
Results = {'year':[],
        'raceId':[],
        'RaceName':[],
        'resultId':[],
        'driverId':[],
        'constructorId':[],
        'number':[],
        'grid':[],     
        'position':[],
        'positionText':[],
        'points':[],
        'laps':[],
        'time':[],
        'miliseconds':[],
        'fastestLap':[],
        'rank':[],
        'fastestLapTime':[],
        'fastestLapSpeed(kph)':[],
        'Status':[]}
urls = []
for i in list(range(2010,2023)):
    url1 = 'http://ergast.com/api/f1/'
    url2 = url1 + str(i)
    url3 = url2 + '.json'
    response = requests.get(url3)
    content = json.loads(response.content)
    for i in list(range(1,len(content['MRData']['RaceTable']['Races'])+1)):
        url4 = url2 + '/' +str(i) + '/results.json?limit=1000' 
        urls.append(url4)
for j in urls:
    response = requests.get(j)
    content=json.loads(response.content)
    for m1 in content['MRData']['RaceTable']['Races']:
        for m2 in content['MRData']['RaceTable']['Races'][0]['Results']:
            Results['year'].append(int(m1['season']))
            Results['raceId'].append(m1['season'] + '_' + m1['round'])
            Results['RaceName'].append(str(m1['raceName']))
            Results['resultId'].append('Result' + '_' + m1['season'] + '_' + m1 ['round'] + '_' + m2['position'])
            Results['position'].append(int(m2['position']))
            Results['positionText'].append(str(m2['positionText']))
            Results['driverId'].append(str(m2['Driver']['driverId']))
            Results['number'].append(int(m2['number']))
            Results['constructorId'].append(str(m2['Constructor']['constructorId']))
            Results['grid'].append(int(m2['grid']))
            Results['points'].append(float(m2['points']))
            Results['laps'].append(int(m2['laps']))
            try:
                Results['time'].append(m2['Time']['time'])
            except:
                Results['time'].append('')
            try:
                Results['miliseconds'].append(m2['Time']['millis'])
            except:
                Results['miliseconds'].append('')
            try:
                Results['fastestLap'].append(m2['FastestLap']['lap'])
            except:
                Results['fastestLap'].append('')
            try:
                Results['rank'].append(m2['FastestLap']['rank'])
            except:
                Results['rank'].append('')
            try:
                Results['fastestLapTime'].append(m2['FastestLap']['Time']['time'])
            except:
                Results['fastestLapTime'].append('')
            try:
                Results['fastestLapSpeed(kph)'].append(m2['FastestLap']['AverageSpeed']['speed'])
            except:
                Results['fastestLapSpeed(kph)'].append('')
            Results['Status'].append(str(m2['status']))
            
        
df = pd.DataFrame(Results)
ConstructorResults=df.groupby(["year","RaceName",'constructorId','Status']).agg({'points':"sum"})
ConstructorResults

                                                       points
year RaceName                 constructorId Status
2010 Abu Dhabi Grand Prix     ferrari       Finished      7.0
                              force_india   Collision     0.0
                                            Finished      0.0
                              hrt           +2 Laps       0.0
                              lotus_racing  +1 Lap        0.0
...                                                       ...
2022 United States Grand Prix haas          Finished      2.0
                              mclaren       Finished      8.0
                              mercedes      Finished     29.0
                              red_bull      Finished     37.0
                              williams      Finished      0.0

[3985 rows x 1 columns]