# <span style='color:red'> <center>f1-Análisis con pandas y json.</center> </span>
### by: **Oliver Iñiguez**

In [1]:
import requests
import json
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
races = {'season':[],
        'round':[],
        'raceName':[],
        'circuitId':[],
        'latitud':[],
        'longitud':[],
        'country':[],
        'date':[],
        'url':[]}

In [3]:
for year in list(range(2010,2023)):
    url = 'http://ergast.com/api/f1/{}.json'
    response = requests.get(url.format(year))
    content = json.loads(response.content)
    for item in content['MRData']['RaceTable']['Races']:
        races['season'].append(int(item['season']))
        races['round'].append(int(item['round']))
        races['raceName'].append(item['raceName'])
        races['circuitId'].append(item['Circuit'].get('circuitId'))
        races['latitud'].append(float(item['Circuit'].get('Location').get('lat')))
        races['longitud'].append(float(item['Circuit'].get('Location').get('long')))
        races['country'].append(item['Circuit'].get('Location').get('country'))
        races['date'].append(pd.to_datetime(item['date']))
        races['url'].append(item['url'])

df = pd.DataFrame.from_dict(races,orient = 'index')
df = df.transpose()
df

,season,round,raceName,circuitId,latitud,longitud,country,date,url
0,2010,1,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2010-03-14,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...
1,2010,2,Australian Grand Prix,albert_park,-37.8497,144.968,Australia,2010-03-28,http://en.wikipedia.org/wiki/2010_Australian_G...
2,2010,3,Malaysian Grand Prix,sepang,2.76083,101.738,Malaysia,2010-04-04,http://en.wikipedia.org/wiki/2010_Malaysian_Gr...
3,2010,4,Chinese Grand Prix,shanghai,31.3389,121.22,China,2010-04-18,http://en.wikipedia.org/wiki/2010_Chinese_Gran...
4,2010,5,Spanish Grand Prix,catalunya,41.57,2.26111,Spain,2010-05-09,http://en.wikipedia.org/wiki/2010_Spanish_Gran...
...,...,...,...,...,...,...,...,...,...
254,2022,18,Japanese Grand Prix,suzuka,34.8431,136.541,Japan,2022-10-09,http://en.wikipedia.org/wiki/2022_Japanese_Gra...
255,2022,19,United States Grand Prix,americas,30.1328,-97.6411,USA,2022-10-23,http://en.wikipedia.org/wiki/2022_United_State...
256,2022,20,Mexico City Grand Prix,rodriguez,19.4042,-99.0907,Mexico,2022-10-30,http://en.wikipedia.org/wiki/2022_Mexican_Gran...
257,2022,21,Brazilian Grand Prix,interlagos,-23.7036,-46.6997,Brazil,2022-11-13,http://en.wikipedia.org/wiki/2022_Brazilian_Gr...
258,2022,22,Abu Dhabi Grand Prix,yas_marina,24.4672,54.6031,UAE,2022-11-20,http://en.wikipedia.org/wiki/2022_Abu_Dhabi_Gr...

In [ ]:
content

In [40]:
Bahrain = df[(df['raceName'] == 'Bahrain Grand Prix') ]
Bahrain

,season,round,raceName,circuitId,latitud,longitud,country,date,url
0,2010,1,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2010-03-14,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...
41,2012,4,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2012-04-22,http://en.wikipedia.org/wiki/2012_Bahrain_Gran...
61,2013,4,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2013-04-21,http://en.wikipedia.org/wiki/2013_Bahrain_Gran...
79,2014,3,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2014-04-06,http://en.wikipedia.org/wiki/2014_Bahrain_Gran...
99,2015,4,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2015-04-19,http://en.wikipedia.org/wiki/2015_Bahrain_Gran...
116,2016,2,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2016-04-03,http://en.wikipedia.org/wiki/2016_Bahrain_Gran...
138,2017,3,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2017-04-16,http://en.wikipedia.org/wiki/2017_Bahrain_Gran...
157,2018,2,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2018-04-08,http://en.wikipedia.org/wiki/2018_Bahrain_Gran...
178,2019,2,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2019-03-31,http://en.wikipedia.org/wiki/2019_Bahrain_Gran...
212,2020,15,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2020-11-29,http://en.wikipedia.org/wiki/2020_Bahrain_Gran...
215,2021,1,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2021-03-28,http://en.wikipedia.org/wiki/2021_Bahrain_Gran...
237,2022,1,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2022-03-20,http://en.wikipedia.org/wiki/2022_Bahrain_Gran...

In [21]:
#Llamando al API
url = 'http://ergast.com/api/f1/2022/22/results.json'
response = requests.get(url)

In [22]:
content = json.loads(response.content)

In [7]:
list(range(1,23))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

In [23]:
df_results_2022 = pd.DataFrame()
for race in list(range(1,23)):
    url = 'http://ergast.com/api/f1/2022/{}/results.json'
    response = requests.get(url.format(race))
    content = json.loads(response.content)
    df_results_2022 = df_results_2022.append(pd.DataFrame(content['MRData']['RaceTable']['Races'][0]['Results']))

In [12]:
content

In [ ]:
df_results_2022

In [25]:
df_results_2022['Driver'] = df_results_2022['Driver'].apply(lambda x: x['driverId'])

In [27]:
df_results_2022['points'] = df_results_2022['points'].astype(int)

In [28]:
df_results_2022.groupby(['Driver']).agg({'points':'sum'}).sort_values(by='points',ascending = False)

                 points
Driver
max_verstappen      433
perez               291
leclerc             291
russell             262
hamilton            233
sainz               228
norris              116
ocon                 89
alonso               81
bottas               47
vettel               37
ricciardo            34
gasly                23
kevin_magnussen      21
stroll               18
tsunoda              12
mick_schumacher      12
zhou                  6
albon                 4
latifi                2
de_vries              2
hulkenberg            0

In [ ]:
df_results_2022

In [30]:
df_results_2022['Constructor'] = df_results_2022['Constructor'].apply(lambda x: x['constructorId'])

In [31]:
df_results_2022.groupby(['Constructor']).agg({'points':'sum'}).sort_values(by='points',ascending = False)

              points
Constructor
red_bull         724
ferrari          519
mercedes         495
alpine           170
mclaren          150
aston_martin      55
alfa              53
alphatauri        35
haas              33
williams           8